sudo: false
os:
- linux
- osx
language: node_js
node_js:
- node
cache:
  yarn: true
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: Wc/ycbV7UWr4y15U/IptNUO8smT6HfEnK5r/g+6gK9pACAZBQvApCgVggCD6krH8BgJJ0zBoi4FYRntKvt08KQ7lk/lwurxNN6P0ZhGrW+OlCZ3XYONnoYRKQnpsoH/wH2XgGknoX/KdgPMLCfvSkRBxlaewTgf42azZhGc+9cfpZt4FRMY2Pl/V0MFFY7C5AZ/uksTrOxq7pLhtO2ySow/6nM9LNkZhytR/RQ/ICGPsC/ckJEvFtgGgqQR2YDrQNGK5JqTwDx2+VQkquoEHNWo6gbNUjb5gQno03VDvW+XQT8/sRgmmkFV7oLWDRe+ongByrGcjPcvHq4oGR3+I0aRyVkAfhg0Mwcv6whOewYU16xI2flKtiQeVxP21AYa4dcdff3SZysqbBsuJ8zb4poZCsQ8dod/aOICC9sOd2vTVIzr/BWIhAIyP6Tx6VjWhQ1NwQjAPwjbiO++45MKKVg7XOlA1lVriJ4FcXOs7jw0mGDXIlB+OMKxZt3SsMUTVHItevf52snfht8qCyOlJ0fSpuVCjUF7LN6Yda/UyeyqaKyPKRPhYI5Ia6J0CbEAbbdfQ3Z9wFVD+ksjHgkc+bjHewQES463mTu6hcDyEinxuimRtukxEzjcYUYuJF667esoWFOnjl4VZ1IFN4iENQkGeFYB0oRaI57hM16zsJUQ=
  app: cbm-clock-demo
  on:
    repo: cbmjs/cbm-clock
    condition: $TRAVIS_OS_NAME = osx
  skip_cleanup: true
notifications:
  email: false
